AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Linkedin job api trend with node.js, crawlee.js. DynamoDB & Api gateway.
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  CrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /test
            Method: get
    Metadata:
      DockerTag: linkendin_job_trend_container
      DockerContext: ./
      Dockerfile: Dockerfile