AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-dynamodb job trend api
Globals:
  Function:
    Timeout: 900
    Environment:
      Variables:
        JOB_SEARCH_TABLE:
          Ref: jobSearchTable
Resources:
  jobSearchTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: jobSearches
      PrimaryKey:
        Name: id
        Type: String
  JobSearchApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, DELETE'''
  jobSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Handler: app.lambdaHandler
      Policies: 
      - Statement:
        - Sid: VisualEditor0
          Effect: Allow
          Action:
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - logs:CreateLogStream
          - logs:CreateLogGroup
          Resource:
          - arn:aws:logs:<aws-region>:<account_id>:log-group:*
          - arn:aws:dynamodb:<aws-region>:<account_id>:table/products
        - Sid: VisualEditor1
          Effect: Allow
          Action:
          - logs:PutLogEvents
          Resource: arn:aws:logs:<aws-region>:<account_id>:log-group:*:log-stream:*
      Events:
        getJobSearch:
          Type: Api
          Properties:
            Path: /jobsearch?keywords={keywords}&location={location}
            Method: get
            RestApiId:
              Ref: JobSearchApi
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  WebEndpoint:
    Description: REST API for search job trend API
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
