AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-dynamodb job trend api
Globals:
  Function:
    Timeout: 900

Resources:
  SearchJobsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        SearchJobs:
          Type: Api
          Properties:
            Path: /search
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  WebEndpoint:
    Description: REST API for search job trend API
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search/"
